version: "3.7"

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - php
    ports:
      - 80:80

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    user: ${UID}:${GID}
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_user
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=root

  composer:
    restart: 'no'
    image: composer:latest
    working_dir: /var/www/source
    command: composer install
    volumes:
      - ./:/var/www


